### ISSUE TITLE
Time span of the dataset.

### ISSUE THREAD

**Issue by AlexCrosby** [AliOsm/AI-SOCO#1]
Hi
I tried to email your google email on your website but it doesn't actually work.

What is the time span that the dataset answers were submitted over? I am trying to figure out a small pattern I have noticed in some user submissions, in which there is a stylistic change throughout the submissions, and I can't tell if it's due to a change in style over time or just due to them being inconsistent. It seems like those with lower pids are older though.

**Comment by AliOsm** [comment]
Hello @AlexCrosby, sorry for the bad experience with our email, we will figure out the problem ASAP.

About the time span, we choose the closest 100 accepted submissions for each user from all submission he/she submitted.

So, in my opinion, the stylistic change is related to the users inconsistent as the submissions time span is minimal.
