### ISSUE TITLE
How to view my submission score???

### ISSUE THREAD

**Issue by DreamweaverWO** [AliOsm/AI-SOCO#3]
My submission all failed. What's the matter?
How do I submit my answers?
The email address（ai-soco-fire@googlegroups.com ） left on the home page is also unable to send mail

**Comment by AliOsm** [comment]
Hello @DreamweaverWO, we are sorry for the bad experience with the email.

About how to submit, please make sure that your submission is similar to the sample submission in [this](https://github.com/AliOsm/AI-SOCO/tree/master/submission_sample) folder. Make sure that the file name is `answer.csv` and it is compressed directly into a `.zip` file.

Let us know if you have any other problems please.

**Comment by AliOsm** [comment]
Also, make sure that you are choosing the right phase, if you want to submit on the development set, then do your submission on `Development` phase, for a test set submission (maximum number of submissions is 3), choose the `Evaluation` phase in CodaLab.
